cart = ["apple", "banana", "milk", "bread", "apple", "eggs"] 
apple_count = cart.count("apple")
print("Number of Apples: ",apple_count)
milk_position = cart.index("milk")
print("Position of milk: ",milk_position)
cart.remove("apple")
print("Removed duplicate apple: ",cart)
removed_item = cart.pop()
print("Removed item using pop: ",removed_item)
print(cart)